version: "3.8"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    image: pmolnar/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    image: pmolnar/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: pmolnar/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      device: /Users/pmolnar/Documents/Universities.nosync/Codam/42cursus/inception/data/wordpress/
      o: bind

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /Users/pmolnar/Documents/Universities.nosync/Codam/42cursus/inception/data/mysql/
      o: bind
